services:
  memobox_db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-memobox}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-memobox}
      POSTGRES_DB: ${POSTGRES_DB:-memobox}
    ports:
      - 5432:5432